[workspace]
members = [
	"prose_core_client",
	"prose_core_domain",
	"prose_core_ffi",
	"prose_core_lib",
	"prose_macros",
	"uniffi-bindgen",
]

[workspace.package]
rust-version = "1.70"

[workspace.dependencies]
anyhow = "1.0"
async-trait = "0.1.68"
base64 = "0.21"
chrono = "0.4"
dotenvy = "0.15"
itertools = "0.10"
jid = { version = "0.9", default-features = false }
libstrophe = "0.17.0"
microtype = "0.7"
once_cell = "1.12"
serde = "1.0"
sha1 = "0.10"
strum = "0.24"
strum_macros = "0.24"
thiserror = "1.0"
tokio = { version = "1.26" }
tracing = { version = "0.1" }
tracing-log = "0.1.3"
tracing-subscriber = "0.3"
uniffi = { git = "https://github.com/mozilla/uniffi-rs", rev = "41e94c0a4834137d8d359b829e2d4b334f5ab5b5" }
url = "2.3"
uuid = {version = "1.1", features=["v4", "fast-rng", "macro-diagnostics"]}