[package]
name = "prose-markup"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true

[dependencies]
jid = { workspace = true }
pulldown-cmark = "0.11"
pulldown-cmark-escape = "0.11"

[dev-dependencies]
insta = "1.39"
pretty_assertions = "1.4"