[bindings.swift]
cdylib_name = "prose_core_ffi"
module_name = "ProseCoreFFI"

[bindings.swift.custom_types.PathBuf]
type_name = "URL"
imports = [ "Foundation" ]
into_custom = "URL(fileURLWithPath: {})"
from_custom = "{}.path"

[bindings.swift.custom_types.Url]
type_name = "URL"
imports = [ "Foundation" ]
into_custom = "URL(string: {})!"
from_custom = "{}.absoluteString"

[bindings.swift.custom_types.DateTime]
type_name = "Date"
imports = [ "Foundation" ]
into_custom = "Date(timeIntervalSince1970: TimeInterval({}) / 1_000)"
from_custom = "Int64({}.timeIntervalSince1970 * 1_000)"

[bindings.swift.custom_types.MessageId]
into_custom = "MessageId({})"
from_custom = "{}.rawValue"

[bindings.swift.custom_types.Emoji]
into_custom = "Emoji({})"
from_custom = "{}.rawValue"