on: [push, pull_request]

name: Test and Build

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-22.04]
        rust-toolchain: [nightly]
      fail-fast: false

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          target: wasm32-unknown-unknown
          components: rustfmt
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.4.0

      - name: Verify versions
        run: rustc --version && rustup --version && cargo --version

      - name: Cache build context
        id: cache-cargo
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: test-${{ runner.os }}-cargo-${{ matrix.rust-toolchain }}

      - name: Check code style
        run: cargo fmt -- --check

      - name: Build crates
        run: cargo build

      - name: Build prose-sdk-js
        run: cargo build --package prose-sdk-js --target wasm32-unknown-unknown

      - name: Build prose-sdk-ffi
        run: cargo build --package prose-sdk-ffi

      - name: Build examples
        run: cargo build --package prose-core-client-cli --package xmpp-client

      - name: Test code
        run: cargo test --features test

      - name: Run core-client integration tests
        run: cargo test --package prose-core-integration-tests

      - name: Run store integration tests
        run: cargo test --package prose-store-integration-tests

      - name: Run Wasm core-client integration tests
        run: cargo xtask ci wasm

      - name: Run Wasm store integration tests
        run: cargo xtask ci wasm-store
